<?xml version="1.0" encoding="utf-8"?><Database Name="Honda_Net_Typer" Class="Honda_Net_Typer_DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.10.248;Initial Catalog=Honda_Net_Typer;Persist Security Info=True;User ID=sa" SettingsObjectName="Honda_Net_Typer.Properties.Settings" SettingsPropertyName="Honda_Net_TyperConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Batch" Member="tbl_Batches">
    <Type Name="tbl_Batch">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fDateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fUserCreate" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fPathPicture" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fLocation" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fSoLuongAnh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MissImage_DeSo" Member="tbl_MissImage_DeSos">
    <Type Name="tbl_MissImage_DeSo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Submit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateInput" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_MissCheck_DeSo" Member="tbl_MissCheck_DeSos">
    <Type Name="tbl_MissCheck_DeSo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Submit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCheck" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Image" Member="tbl_Images">
    <Type Name="tbl_Image">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserNameDeSo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ReadImageDeSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckedDeSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienDoDeSo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DeSo" Member="tbl_DeSos">
    <Type Name="tbl_DeSo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdPhieu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Truong_01" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Dem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Error" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="True" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateInput" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DeSo_BackUp" Member="tbl_DeSo_BackUps">
    <Type Name="tbl_DeSo_BackUp">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdPhieu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Truong_01" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Dem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Error" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="True" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateInput" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetBatch" Method="GetBatch">
    <ElementType Name="GetBatchResult">
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetBatNotFinishDeSo" Method="GetBatNotFinishDeSo">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="GetBatNotFinishDeSoResult">
      <Column Name="fbatchname" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fBatchName1" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="fDateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fUserCreate" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fPathPicture" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fLocation" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="fSoLuongAnh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetBatNotFinishCheckerDeSo" Method="GetBatNotFinishCheckerDeSo">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="GetBatNotFinishCheckerDeSoResult">
      <Column Name="fbatchname" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LayHinhMoi_DeSo" Method="LayHinhMoi_DeSo">
    <Parameter Name="fbatchname" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="username" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="LayHinhMoi_DeSoResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSoLoi_CheckDe" Method="GetSoLoi_CheckDe">
    <Parameter Name="fBatchName" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="GetSoLoi_CheckDeResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetImageCheck_DeSo" Method="GetImageCheck_DeSo">
    <Parameter Name="fBatchName" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(250)" />
    <ElementType Name="GetImageCheck_DeSoResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Load_Check_DeSo" Method="Load_Check_DeSo">
    <Parameter Name="fBatchName" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="IdImage" Parameter="idImage" Type="System.String" DbType="NVarChar(250)" />
    <ElementType Name="Load_Check_DeSoResult">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Truong_01" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IdPhieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LuuDeSo" Method="LuuDeSo">
    <Parameter Name="IdImage" Parameter="idImage" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="fBatchName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserNameDung" Parameter="userNameDung" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserNameSai" Parameter="userNameSai" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserChecker" Parameter="userChecker" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InputFinish" Method="InputFinish">
    <Parameter Name="fbatchname" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckerFinish" Method="CheckerFinish">
    <Parameter Name="fbatchname" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaBatch" Method="XoaBatch">
    <Parameter Name="fbatchname" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Insert_Data_DeSo" Method="Insert_Data_DeSo">
    <Parameter Name="IdImage" Parameter="idImage" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="fBatchName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu1" Parameter="truong1_Phieu1" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu2" Parameter="truong1_Phieu2" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu3" Parameter="truong1_Phieu3" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu4" Parameter="truong1_Phieu4" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu5" Parameter="truong1_Phieu5" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu6" Parameter="truong1_Phieu6" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu7" Parameter="truong1_Phieu7" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu8" Parameter="truong1_Phieu8" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu9" Parameter="truong1_Phieu9" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu10" Parameter="truong1_Phieu10" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu11" Parameter="truong1_Phieu11" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong1_Phieu12" Parameter="truong1_Phieu12" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaVaLuu" Method="SuaVaLuu">
    <Parameter Name="UserSaiIt" Parameter="userSaiIt" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserSaiNhieu" Parameter="userSaiNhieu" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IdImage" Parameter="idImage" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="fBatchName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserCheck" Parameter="userCheck" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_1" Parameter="truong_01_1" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_2" Parameter="truong_01_2" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_3" Parameter="truong_01_3" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_4" Parameter="truong_01_4" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_5" Parameter="truong_01_5" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_6" Parameter="truong_01_6" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_7" Parameter="truong_01_7" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_8" Parameter="truong_01_8" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_9" Parameter="truong_01_9" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_10" Parameter="truong_01_10" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_11" Parameter="truong_01_11" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_12" Parameter="truong_01_12" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaVaLuu_New" Method="SuaVaLuu_New">
    <Parameter Name="UserSaiIt" Parameter="userSaiIt" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserSaiNhieu" Parameter="userSaiNhieu" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IdImage" Parameter="idImage" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="fBatchName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserCheck" Parameter="userCheck" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_1" Parameter="truong_01_1" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_2" Parameter="truong_01_2" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_3" Parameter="truong_01_3" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_4" Parameter="truong_01_4" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_5" Parameter="truong_01_5" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_6" Parameter="truong_01_6" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_7" Parameter="truong_01_7" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_8" Parameter="truong_01_8" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_9" Parameter="truong_01_9" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_10" Parameter="truong_01_10" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_11" Parameter="truong_01_11" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Truong_01_12" Parameter="truong_01_12" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExportExcel" Method="ExportExcel">
    <Parameter Name="fBatchName" Type="System.String" DbType="NVarChar(250)" />
    <ElementType Name="ExportExcelResult">
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Truong_01" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IdPhieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportExcel_New" Method="ExportExcel_New">
    <Parameter Name="fbatchname" Type="System.String" DbType="NVarChar(250)" />
    <ElementType Name="ExportExcel_NewResult">
      <Column Name="IdImage" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Truong_01" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IdPhieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.NangSuatDeSo" Method="NangSuatDeSo">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="NangSuatDeSoResult">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoPhieuNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhieuDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhieuSai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="HieuSuat" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongKeTienDo_All" Method="ThongKeTienDo_All">
    <ElementType Name="ThongKeTienDo_AllResult">
      <Column Name="name" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongKeTienDo" Method="ThongKeTienDo">
    <Parameter Name="fbatchname" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="ThongKeTienDoResult">
      <Column Name="name" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChiTietUserDeSo" Method="ChiTietUserDeSo">
    <Parameter Name="fbatchname" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="idimage" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="ChiTietUserDeSoResult">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChiTietTienDo_All" Method="ChiTietTienDo_All">
    <ElementType Name="ChiTietTienDo_AllResult">
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="idimage" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserNameDESo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Checker" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DateCheck" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThongTin" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChiTietTienDo" Method="ChiTietTienDo">
    <Parameter Name="fbatchname" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="ChiTietTienDoResult">
      <Column Name="fBatchName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="idimage" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserNameDESo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Checker" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DateCheck" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThongTin" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>