#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honda_Net_Typer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Honda_Net_Typer")]
	public partial class Honda_Net_Typer_DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Batch(tbl_Batch instance);
    partial void Updatetbl_Batch(tbl_Batch instance);
    partial void Deletetbl_Batch(tbl_Batch instance);
    partial void Inserttbl_MissImage_DeSo(tbl_MissImage_DeSo instance);
    partial void Updatetbl_MissImage_DeSo(tbl_MissImage_DeSo instance);
    partial void Deletetbl_MissImage_DeSo(tbl_MissImage_DeSo instance);
    partial void Inserttbl_Image(tbl_Image instance);
    partial void Updatetbl_Image(tbl_Image instance);
    partial void Deletetbl_Image(tbl_Image instance);
    partial void Inserttbl_DeSo(tbl_DeSo instance);
    partial void Updatetbl_DeSo(tbl_DeSo instance);
    partial void Deletetbl_DeSo(tbl_DeSo instance);
    partial void Inserttbl_DeSo_BackUp(tbl_DeSo_BackUp instance);
    partial void Updatetbl_DeSo_BackUp(tbl_DeSo_BackUp instance);
    partial void Deletetbl_DeSo_BackUp(tbl_DeSo_BackUp instance);
    #endregion
		
		public Honda_Net_Typer_DataDataContext() : 
				base(global::Honda_Net_Typer.Properties.Settings.Default.Honda_Net_TyperConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Honda_Net_Typer_DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Honda_Net_Typer_DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Honda_Net_Typer_DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Honda_Net_Typer_DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Batch> tbl_Batches
		{
			get
			{
				return this.GetTable<tbl_Batch>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MissImage_DeSo> tbl_MissImage_DeSos
		{
			get
			{
				return this.GetTable<tbl_MissImage_DeSo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_MissCheck_DeSo> tbl_MissCheck_DeSos
		{
			get
			{
				return this.GetTable<tbl_MissCheck_DeSo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Image> tbl_Images
		{
			get
			{
				return this.GetTable<tbl_Image>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DeSo> tbl_DeSos
		{
			get
			{
				return this.GetTable<tbl_DeSo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DeSo_BackUp> tbl_DeSo_BackUps
		{
			get
			{
				return this.GetTable<tbl_DeSo_BackUp>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetBatch")]
		public ISingleResult<GetBatchResult> GetBatch()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetBatchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetBatNotFinishDeSo")]
		public ISingleResult<GetBatNotFinishDeSoResult> GetBatNotFinishDeSo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((ISingleResult<GetBatNotFinishDeSoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetBatNotFinishCheckerDeSo")]
		public ISingleResult<GetBatNotFinishCheckerDeSoResult> GetBatNotFinishCheckerDeSo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((ISingleResult<GetBatNotFinishCheckerDeSoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LayHinhMoi_DeSo")]
		public ISingleResult<LayHinhMoi_DeSoResult> LayHinhMoi_DeSo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fbatchname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fbatchname, username);
			return ((ISingleResult<LayHinhMoi_DeSoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSoLoi_CheckDe")]
		public ISingleResult<GetSoLoi_CheckDeResult> GetSoLoi_CheckDe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fBatchName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fBatchName);
			return ((ISingleResult<GetSoLoi_CheckDeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetImageCheck_DeSo")]
		public ISingleResult<GetImageCheck_DeSoResult> GetImageCheck_DeSo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string fBatchName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(250)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fBatchName, userName);
			return ((ISingleResult<GetImageCheck_DeSoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Load_Check_DeSo")]
		public ISingleResult<Load_Check_DeSoResult> Load_Check_DeSo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string fBatchName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdImage", DbType="NVarChar(250)")] string idImage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fBatchName, idImage);
			return ((ISingleResult<Load_Check_DeSoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LuuDeSo")]
		public int LuuDeSo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdImage", DbType="NVarChar(255)")] string idImage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fBatchName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserNameDung", DbType="NVarChar(255)")] string userNameDung, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserNameSai", DbType="NVarChar(255)")] string userNameSai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserChecker", DbType="NVarChar(255)")] string userChecker)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idImage, fBatchName, userNameDung, userNameSai, userChecker);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InputFinish")]
		public int InputFinish([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string fbatchname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fbatchname);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckerFinish")]
		public int CheckerFinish([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string fbatchname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fbatchname);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XoaBatch")]
		public int XoaBatch([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fbatchname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fbatchname);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insert_Data_DeSo")]
		public int Insert_Data_DeSo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdImage", DbType="NVarChar(255)")] string idImage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fBatchName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(255)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu1", DbType="NVarChar(255)")] string truong1_Phieu1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu2", DbType="NVarChar(255)")] string truong1_Phieu2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu3", DbType="NVarChar(255)")] string truong1_Phieu3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu4", DbType="NVarChar(255)")] string truong1_Phieu4, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu5", DbType="NVarChar(255)")] string truong1_Phieu5, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu6", DbType="NVarChar(255)")] string truong1_Phieu6, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu7", DbType="NVarChar(255)")] string truong1_Phieu7, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu8", DbType="NVarChar(255)")] string truong1_Phieu8, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu9", DbType="NVarChar(255)")] string truong1_Phieu9, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu10", DbType="NVarChar(255)")] string truong1_Phieu10, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu11", DbType="NVarChar(255)")] string truong1_Phieu11, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong1_Phieu12", DbType="NVarChar(255)")] string truong1_Phieu12)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idImage, fBatchName, userName, truong1_Phieu1, truong1_Phieu2, truong1_Phieu3, truong1_Phieu4, truong1_Phieu5, truong1_Phieu6, truong1_Phieu7, truong1_Phieu8, truong1_Phieu9, truong1_Phieu10, truong1_Phieu11, truong1_Phieu12);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SuaVaLuu")]
		public int SuaVaLuu(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserSaiIt", DbType="NVarChar(255)")] string userSaiIt, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserSaiNhieu", DbType="NVarChar(255)")] string userSaiNhieu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdImage", DbType="NVarChar(255)")] string idImage, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fBatchName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserCheck", DbType="NVarChar(255)")] string userCheck, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_1", DbType="NVarChar(255)")] string truong_01_1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_2", DbType="NVarChar(255)")] string truong_01_2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_3", DbType="NVarChar(255)")] string truong_01_3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_4", DbType="NVarChar(255)")] string truong_01_4, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_5", DbType="NVarChar(255)")] string truong_01_5, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_6", DbType="NVarChar(255)")] string truong_01_6, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_7", DbType="NVarChar(255)")] string truong_01_7, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_8", DbType="NVarChar(255)")] string truong_01_8, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_9", DbType="NVarChar(255)")] string truong_01_9, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_10", DbType="NVarChar(255)")] string truong_01_10, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_11", DbType="NVarChar(255)")] string truong_01_11, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_12", DbType="NVarChar(255)")] string truong_01_12)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userSaiIt, userSaiNhieu, idImage, fBatchName, userCheck, truong_01_1, truong_01_2, truong_01_3, truong_01_4, truong_01_5, truong_01_6, truong_01_7, truong_01_8, truong_01_9, truong_01_10, truong_01_11, truong_01_12);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SuaVaLuu_New")]
		public int SuaVaLuu_New(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserSaiIt", DbType="NVarChar(255)")] string userSaiIt, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserSaiNhieu", DbType="NVarChar(255)")] string userSaiNhieu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdImage", DbType="NVarChar(255)")] string idImage, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fBatchName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserCheck", DbType="NVarChar(255)")] string userCheck, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_1", DbType="NVarChar(255)")] string truong_01_1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_2", DbType="NVarChar(255)")] string truong_01_2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_3", DbType="NVarChar(255)")] string truong_01_3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_4", DbType="NVarChar(255)")] string truong_01_4, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_5", DbType="NVarChar(255)")] string truong_01_5, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_6", DbType="NVarChar(255)")] string truong_01_6, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_7", DbType="NVarChar(255)")] string truong_01_7, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_8", DbType="NVarChar(255)")] string truong_01_8, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_9", DbType="NVarChar(255)")] string truong_01_9, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_10", DbType="NVarChar(255)")] string truong_01_10, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_11", DbType="NVarChar(255)")] string truong_01_11, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Truong_01_12", DbType="NVarChar(255)")] string truong_01_12)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userSaiIt, userSaiNhieu, idImage, fBatchName, userCheck, truong_01_1, truong_01_2, truong_01_3, truong_01_4, truong_01_5, truong_01_6, truong_01_7, truong_01_8, truong_01_9, truong_01_10, truong_01_11, truong_01_12);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ExportExcel")]
		public ISingleResult<ExportExcelResult> ExportExcel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string fBatchName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fBatchName);
			return ((ISingleResult<ExportExcelResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ExportExcel_New")]
		public ISingleResult<ExportExcel_NewResult> ExportExcel_New([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string fbatchname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fbatchname);
			return ((ISingleResult<ExportExcel_NewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NangSuatDeSo")]
		public ISingleResult<NangSuatDeSoResult> NangSuatDeSo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="DateTime")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="DateTime")] System.Nullable<System.DateTime> denNgay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tuNgay, denNgay);
			return ((ISingleResult<NangSuatDeSoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThongKeTienDo_All")]
		public ISingleResult<ThongKeTienDo_AllResult> ThongKeTienDo_All()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ThongKeTienDo_AllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThongKeTienDo")]
		public ISingleResult<ThongKeTienDoResult> ThongKeTienDo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fbatchname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fbatchname);
			return ((ISingleResult<ThongKeTienDoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietTienDo")]
		public ISingleResult<ChiTietTienDoResult> ChiTietTienDo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fbatchname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fbatchname);
			return ((ISingleResult<ChiTietTienDoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietUserDeSo")]
		public ISingleResult<ChiTietUserDeSoResult> ChiTietUserDeSo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string fbatchname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string idimage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fbatchname, idimage);
			return ((ISingleResult<ChiTietUserDeSoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietTienDo_All")]
		public ISingleResult<ChiTietTienDo_AllResult> ChiTietTienDo_All()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ChiTietTienDo_AllResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Batch")]
	public partial class tbl_Batch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _fBatchName;
		
		private System.Nullable<System.DateTime> _fDateCreate;
		
		private string _fUserCreate;
		
		private string _fPathPicture;
		
		private string _fLocation;
		
		private string _fSoLuongAnh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnfDateCreateChanging(System.Nullable<System.DateTime> value);
    partial void OnfDateCreateChanged();
    partial void OnfUserCreateChanging(string value);
    partial void OnfUserCreateChanged();
    partial void OnfPathPictureChanging(string value);
    partial void OnfPathPictureChanged();
    partial void OnfLocationChanging(string value);
    partial void OnfLocationChanged();
    partial void OnfSoLuongAnhChanging(string value);
    partial void OnfSoLuongAnhChanged();
    #endregion
		
		public tbl_Batch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDateCreate", DbType="DateTime")]
		public System.Nullable<System.DateTime> fDateCreate
		{
			get
			{
				return this._fDateCreate;
			}
			set
			{
				if ((this._fDateCreate != value))
				{
					this.OnfDateCreateChanging(value);
					this.SendPropertyChanging();
					this._fDateCreate = value;
					this.SendPropertyChanged("fDateCreate");
					this.OnfDateCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fUserCreate", DbType="NVarChar(200)")]
		public string fUserCreate
		{
			get
			{
				return this._fUserCreate;
			}
			set
			{
				if ((this._fUserCreate != value))
				{
					this.OnfUserCreateChanging(value);
					this.SendPropertyChanging();
					this._fUserCreate = value;
					this.SendPropertyChanged("fUserCreate");
					this.OnfUserCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPathPicture", DbType="NVarChar(200)")]
		public string fPathPicture
		{
			get
			{
				return this._fPathPicture;
			}
			set
			{
				if ((this._fPathPicture != value))
				{
					this.OnfPathPictureChanging(value);
					this.SendPropertyChanging();
					this._fPathPicture = value;
					this.SendPropertyChanged("fPathPicture");
					this.OnfPathPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fLocation", DbType="NVarChar(200)")]
		public string fLocation
		{
			get
			{
				return this._fLocation;
			}
			set
			{
				if ((this._fLocation != value))
				{
					this.OnfLocationChanging(value);
					this.SendPropertyChanging();
					this._fLocation = value;
					this.SendPropertyChanged("fLocation");
					this.OnfLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fSoLuongAnh", DbType="NVarChar(200)")]
		public string fSoLuongAnh
		{
			get
			{
				return this._fSoLuongAnh;
			}
			set
			{
				if ((this._fSoLuongAnh != value))
				{
					this.OnfSoLuongAnhChanging(value);
					this.SendPropertyChanging();
					this._fSoLuongAnh = value;
					this.SendPropertyChanged("fSoLuongAnh");
					this.OnfSoLuongAnhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissImage_DeSo")]
	public partial class tbl_MissImage_DeSo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private System.Nullable<int> _Submit;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnSubmitChanging(System.Nullable<int> value);
    partial void OnSubmitChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_MissImage_DeSo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="Int")]
		public System.Nullable<int> Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this.OnSubmitChanging(value);
					this.SendPropertyChanging();
					this._Submit = value;
					this.SendPropertyChanged("Submit");
					this.OnSubmitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MissCheck_DeSo")]
	public partial class tbl_MissCheck_DeSo
	{
		
		private int _Id;
		
		private string _IdImage;
		
		private string _fBatchName;
		
		private string _UserName;
		
		private System.Nullable<int> _Submit;
		
		private System.Nullable<System.DateTime> _DateCheck;
		
		public tbl_MissCheck_DeSo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(200)")]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this._IdImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(200)")]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this._fBatchName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(200)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submit", DbType="Int")]
		public System.Nullable<int> Submit
		{
			get
			{
				return this._Submit;
			}
			set
			{
				if ((this._Submit != value))
				{
					this._Submit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCheck", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCheck
		{
			get
			{
				return this._DateCheck;
			}
			set
			{
				if ((this._DateCheck != value))
				{
					this._DateCheck = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Image")]
	public partial class tbl_Image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _fBatchName;
		
		private string _IdImage;
		
		private string _UserNameDeSo;
		
		private System.Nullable<int> _ReadImageDeSo;
		
		private System.Nullable<int> _CheckedDeSo;
		
		private string _TienDoDeSo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnUserNameDeSoChanging(string value);
    partial void OnUserNameDeSoChanged();
    partial void OnReadImageDeSoChanging(System.Nullable<int> value);
    partial void OnReadImageDeSoChanged();
    partial void OnCheckedDeSoChanging(System.Nullable<int> value);
    partial void OnCheckedDeSoChanged();
    partial void OnTienDoDeSoChanging(string value);
    partial void OnTienDoDeSoChanged();
    #endregion
		
		public tbl_Image()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameDeSo", DbType="NVarChar(200)")]
		public string UserNameDeSo
		{
			get
			{
				return this._UserNameDeSo;
			}
			set
			{
				if ((this._UserNameDeSo != value))
				{
					this.OnUserNameDeSoChanging(value);
					this.SendPropertyChanging();
					this._UserNameDeSo = value;
					this.SendPropertyChanged("UserNameDeSo");
					this.OnUserNameDeSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadImageDeSo", DbType="Int")]
		public System.Nullable<int> ReadImageDeSo
		{
			get
			{
				return this._ReadImageDeSo;
			}
			set
			{
				if ((this._ReadImageDeSo != value))
				{
					this.OnReadImageDeSoChanging(value);
					this.SendPropertyChanging();
					this._ReadImageDeSo = value;
					this.SendPropertyChanged("ReadImageDeSo");
					this.OnReadImageDeSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckedDeSo", DbType="Int")]
		public System.Nullable<int> CheckedDeSo
		{
			get
			{
				return this._CheckedDeSo;
			}
			set
			{
				if ((this._CheckedDeSo != value))
				{
					this.OnCheckedDeSoChanging(value);
					this.SendPropertyChanging();
					this._CheckedDeSo = value;
					this.SendPropertyChanged("CheckedDeSo");
					this.OnCheckedDeSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDoDeSo", DbType="NVarChar(200)")]
		public string TienDoDeSo
		{
			get
			{
				return this._TienDoDeSo;
			}
			set
			{
				if ((this._TienDoDeSo != value))
				{
					this.OnTienDoDeSoChanging(value);
					this.SendPropertyChanging();
					this._TienDoDeSo = value;
					this.SendPropertyChanged("TienDoDeSo");
					this.OnTienDoDeSoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DeSo")]
	public partial class tbl_DeSo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _IdImage;
		
		private string _UserName;
		
		private string _fBatchName;
		
		private int _IdPhieu;
		
		private string _Truong_01;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnIdPhieuChanging(int value);
    partial void OnIdPhieuChanged();
    partial void OnTruong_01Changing(string value);
    partial void OnTruong_01Changed();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_DeSo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(200)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this.OnTruong_01Changing(value);
					this.SendPropertyChanging();
					this._Truong_01 = value;
					this.SendPropertyChanged("Truong_01");
					this.OnTruong_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DeSo_BackUp")]
	public partial class tbl_DeSo_BackUp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _IdImage;
		
		private string _UserName;
		
		private string _fBatchName;
		
		private int _IdPhieu;
		
		private string _Truong_01;
		
		private System.Nullable<int> _Dem;
		
		private System.Nullable<int> _Error;
		
		private System.Nullable<int> _True;
		
		private System.Nullable<System.DateTime> _DateInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdImageChanging(string value);
    partial void OnIdImageChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnfBatchNameChanging(string value);
    partial void OnfBatchNameChanged();
    partial void OnIdPhieuChanging(int value);
    partial void OnIdPhieuChanged();
    partial void OnTruong_01Changing(string value);
    partial void OnTruong_01Changed();
    partial void OnDemChanging(System.Nullable<int> value);
    partial void OnDemChanged();
    partial void OnErrorChanging(System.Nullable<int> value);
    partial void OnErrorChanged();
    partial void OnTrueChanging(System.Nullable<int> value);
    partial void OnTrueChanged();
    partial void OnDateInputChanging(System.Nullable<System.DateTime> value);
    partial void OnDateInputChanged();
    #endregion
		
		public tbl_DeSo_BackUp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this.OnfBatchNameChanging(value);
					this.SendPropertyChanging();
					this._fBatchName = value;
					this.SendPropertyChanged("fBatchName");
					this.OnfBatchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(200)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this.OnTruong_01Changing(value);
					this.SendPropertyChanging();
					this._Truong_01 = value;
					this.SendPropertyChanged("Truong_01");
					this.OnTruong_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dem", DbType="Int")]
		public System.Nullable<int> Dem
		{
			get
			{
				return this._Dem;
			}
			set
			{
				if ((this._Dem != value))
				{
					this.OnDemChanging(value);
					this.SendPropertyChanging();
					this._Dem = value;
					this.SendPropertyChanged("Dem");
					this.OnDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Int")]
		public System.Nullable<int> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True", DbType="Int")]
		public System.Nullable<int> True
		{
			get
			{
				return this._True;
			}
			set
			{
				if ((this._True != value))
				{
					this.OnTrueChanging(value);
					this.SendPropertyChanging();
					this._True = value;
					this.SendPropertyChanged("True");
					this.OnTrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInput", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateInput
		{
			get
			{
				return this._DateInput;
			}
			set
			{
				if ((this._DateInput != value))
				{
					this.OnDateInputChanging(value);
					this.SendPropertyChanging();
					this._DateInput = value;
					this.SendPropertyChanged("DateInput");
					this.OnDateInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetBatchResult
	{
		
		private string _fBatchName;
		
		public GetBatchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string fBatchName
		{
			get
			{
				return this._fBatchName;
			}
			set
			{
				if ((this._fBatchName != value))
				{
					this._fBatchName = value;
				}
			}
		}
	}
	
	public partial class GetBatNotFinishDeSoResult
	{
		
		private string _fbatchname;
		
		private int _id;
		
		private string _fBatchName1;
		
		private System.Nullable<System.DateTime> _fDateCreate;
		
		private string _fUserCreate;
		
		private string _fPathPicture;
		
		private string _fLocation;
		
		private string _fSoLuongAnh;
		
		public GetBatNotFinishDeSoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fbatchname", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string fbatchname
		{
			get
			{
				return this._fbatchname;
			}
			set
			{
				if ((this._fbatchname != value))
				{
					this._fbatchname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fBatchName1", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string fBatchName1
		{
			get
			{
				return this._fBatchName1;
			}
			set
			{
				if ((this._fBatchName1 != value))
				{
					this._fBatchName1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDateCreate", DbType="DateTime")]
		public System.Nullable<System.DateTime> fDateCreate
		{
			get
			{
				return this._fDateCreate;
			}
			set
			{
				if ((this._fDateCreate != value))
				{
					this._fDateCreate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fUserCreate", DbType="NVarChar(200)")]
		public string fUserCreate
		{
			get
			{
				return this._fUserCreate;
			}
			set
			{
				if ((this._fUserCreate != value))
				{
					this._fUserCreate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPathPicture", DbType="NVarChar(200)")]
		public string fPathPicture
		{
			get
			{
				return this._fPathPicture;
			}
			set
			{
				if ((this._fPathPicture != value))
				{
					this._fPathPicture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fLocation", DbType="NVarChar(200)")]
		public string fLocation
		{
			get
			{
				return this._fLocation;
			}
			set
			{
				if ((this._fLocation != value))
				{
					this._fLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fSoLuongAnh", DbType="NVarChar(200)")]
		public string fSoLuongAnh
		{
			get
			{
				return this._fSoLuongAnh;
			}
			set
			{
				if ((this._fSoLuongAnh != value))
				{
					this._fSoLuongAnh = value;
				}
			}
		}
	}
	
	public partial class GetBatNotFinishCheckerDeSoResult
	{
		
		private string _fbatchname;
		
		public GetBatNotFinishCheckerDeSoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fbatchname", DbType="NVarChar(200)")]
		public string fbatchname
		{
			get
			{
				return this._fbatchname;
			}
			set
			{
				if ((this._fbatchname != value))
				{
					this._fbatchname = value;
				}
			}
		}
	}
	
	public partial class LayHinhMoi_DeSoResult
	{
		
		private string _Column1;
		
		public LayHinhMoi_DeSoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="NVarChar(255)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class GetSoLoi_CheckDeResult
	{
		
		private System.Nullable<int> _Column1;
		
		public GetSoLoi_CheckDeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class GetImageCheck_DeSoResult
	{
		
		private string _Column1;
		
		public GetImageCheck_DeSoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="NVarChar(250)")]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class Load_Check_DeSoResult
	{
		
		private string _UserName;
		
		private string _Truong_01;
		
		private System.Nullable<int> _IdPhieu;
		
		public Load_Check_DeSoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(200)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this._Truong_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int")]
		public System.Nullable<int> IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this._IdPhieu = value;
				}
			}
		}
	}
	
	public partial class ExportExcelResult
	{
		
		private string _IdImage;
		
		private string _Truong_01;
		
		private int _IdPhieu;
		
		public ExportExcelResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this._IdImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(200)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this._Truong_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int NOT NULL")]
		public int IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this._IdPhieu = value;
				}
			}
		}
	}
	
	public partial class ExportExcel_NewResult
	{
		
		private string _IdImage;
		
		private string _Truong_01;
		
		private int _IdPhieu;
		
		public ExportExcel_NewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this._IdImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong_01", DbType="NVarChar(200)")]
		public string Truong_01
		{
			get
			{
				return this._Truong_01;
			}
			set
			{
				if ((this._Truong_01 != value))
				{
					this._Truong_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", DbType="Int NOT NULL")]
		public int IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this._IdPhieu = value;
				}
			}
		}
	}
	
	public partial class NangSuatDeSoResult
	{
		
		private string _UserName;
		
		private string _FullName;
		
		private System.Nullable<int> _SoPhieuNhap;
		
		private System.Nullable<int> _PhieuDung;
		
		private System.Nullable<int> _PhieuSai;
		
		private string _ThoiGian;
		
		private System.Nullable<double> _HieuSuat;
		
		public NangSuatDeSoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(100)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuNhap", DbType="Int")]
		public System.Nullable<int> SoPhieuNhap
		{
			get
			{
				return this._SoPhieuNhap;
			}
			set
			{
				if ((this._SoPhieuNhap != value))
				{
					this._SoPhieuNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhieuDung", DbType="Int")]
		public System.Nullable<int> PhieuDung
		{
			get
			{
				return this._PhieuDung;
			}
			set
			{
				if ((this._PhieuDung != value))
				{
					this._PhieuDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhieuSai", DbType="Int")]
		public System.Nullable<int> PhieuSai
		{
			get
			{
				return this._PhieuSai;
			}
			set
			{
				if ((this._PhieuSai != value))
				{
					this._PhieuSai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="NVarChar(30)")]
		public string ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this._ThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HieuSuat", DbType="Float")]
		public System.Nullable<double> HieuSuat
		{
			get
			{
				return this._HieuSuat;
			}
			set
			{
				if ((this._HieuSuat != value))
				{
					this._HieuSuat = value;
				}
			}
		}
	}
	
	public partial class ThongKeTienDo_AllResult
	{
		
		private string _name;
		
		private int _soluong;
		
		public ThongKeTienDo_AllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
	}
	
	public partial class ThongKeTienDoResult
	{
		
		private string _name;
		
		private int _soluong;
		
		public ThongKeTienDoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
	}
	
	public partial class ChiTietTienDoResult
	{
		
		private string _idimage;
		
		private string _UserNameDESo;
		
		private string _Checker;
		
		private System.Nullable<System.DateTime> _DateCheck;
		
		private string _ThongTin;
		
		public ChiTietTienDoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idimage", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string idimage
		{
			get
			{
				return this._idimage;
			}
			set
			{
				if ((this._idimage != value))
				{
					this._idimage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameDESo", DbType="NVarChar(200)")]
		public string UserNameDESo
		{
			get
			{
				return this._UserNameDESo;
			}
			set
			{
				if ((this._UserNameDESo != value))
				{
					this._UserNameDESo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checker", DbType="NVarChar(200)")]
		public string Checker
		{
			get
			{
				return this._Checker;
			}
			set
			{
				if ((this._Checker != value))
				{
					this._Checker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCheck", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCheck
		{
			get
			{
				return this._DateCheck;
			}
			set
			{
				if ((this._DateCheck != value))
				{
					this._DateCheck = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(200)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this._ThongTin = value;
				}
			}
		}
	}
	
	public partial class ChiTietUserDeSoResult
	{
		
		private string _UserName;
		
		public ChiTietUserDeSoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
	}
	
	public partial class ChiTietTienDo_AllResult
	{
		
		private string _idimage;
		
		private string _UserNameDESo;
		
		private string _Checker;
		
		private System.Nullable<System.DateTime> _DateCheck;
		
		private string _ThongTin;
		
		public ChiTietTienDo_AllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idimage", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string idimage
		{
			get
			{
				return this._idimage;
			}
			set
			{
				if ((this._idimage != value))
				{
					this._idimage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameDESo", DbType="NVarChar(200)")]
		public string UserNameDESo
		{
			get
			{
				return this._UserNameDESo;
			}
			set
			{
				if ((this._UserNameDESo != value))
				{
					this._UserNameDESo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checker", DbType="NVarChar(200)")]
		public string Checker
		{
			get
			{
				return this._Checker;
			}
			set
			{
				if ((this._Checker != value))
				{
					this._Checker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCheck", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCheck
		{
			get
			{
				return this._DateCheck;
			}
			set
			{
				if ((this._DateCheck != value))
				{
					this._DateCheck = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(200)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this._ThongTin = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
